@extends('layouts.frontend.master')


@if(Request::is('user/account'))
  @section('title',  trans('frontend.frontend_user_dashboard_title') .' < '. get_site_title() )
@elseif (Request::is('user/account/dashboard'))
  @section('title',  trans('frontend.frontend_user_dashboard_title') .' < '. get_site_title() )
@elseif (Request::is('user/account/my-address'))
  @section('title',  trans('frontend.frontend_user_address_title') .' < '. get_site_title() )
@elseif (Request::is('user/account/my-address/add'))
  @section('title',  trans('frontend.frontend_user_address_add_title') .' < '. get_site_title() ) 
@elseif (Request::is('user/account/my-address/edit'))
  @section('title',  trans('frontend.frontend_user_address_edit_title') .' < '. get_site_title() )
@elseif (Request::is('user/account/my-profile'))
  @section('title',  trans('frontend.frontend_user_profile_edit_title') .' < '. get_site_title() )
  @section('page-wrapper', 'dashboard-wrapper')
@elseif (Request::is('user/account/my-orders'))
  @section('page-wrapper', 'dashboard-wrapper')
  @section('title',  trans('frontend.frontend_my_order_title') .' < '. get_site_title() )
@elseif (Request::is('user/account/my-saved-items'))
  @section('title',  trans('frontend.frontend_wishlist_items_title') .' < '. get_site_title() ) 
  @section('page-wrapper', 'cart-page-wrapper')
@elseif (Request::is('user/account/my-coupons'))
  @section('title',  trans('frontend.frontend_coupons_items_title') .' < '. get_site_title() )
@elseif (Request::is('user/account/download'))
  @section('title',  trans('frontend.frontend_download_options_title') .' < '. get_site_title() )  
@elseif(Request::is('user/account/order-details/*'))
  @section('title',  trans('frontend.user_order_details_page_title') .' < '. get_site_title() )  
@endif

@section('content')
@if(Request::is('user/account/dashboard') || Request::is('user/account'))
            {{-- @include('pages.frontend.user-account.my-dashboard') --}}
            @include('pages.frontend.user-account.user-profile')
          @elseif(Request::is('user/account/my-address'))  
            @include('pages.frontend.user-account.my-address')
          @elseif(Request::is('user/account/my-address/add'))  
            @include('pages.frontend.user-account.add-address')
          @elseif(Request::is('user/account/my-address/edit'))  
            @include('pages.frontend.user-account.edit-address')
          @elseif(Request::is('user/account/my-profile') )  
            @include('pages.frontend.user-account.user-profile')  
          @elseif(Request::is('user/account/my-orders') )
            @include('pages.frontend.user-account.my-orders') 
          @elseif(Request::is('user/account/view-orders-details/*') )
            @include('pages.frontend.user-account.user-order-details')
          @elseif(Request::is('user/account/my-saved-items') )
            @include('pages.frontend.user-account.my-wishlist') 
          @elseif(Request::is('user/account/my-coupons') )
            @include('pages.frontend.user-account.my-coupons')
          @elseif(Request::is('user/account/download') )
            @include('pages.frontend.user-account.download')  
          @elseif(Request::is('user/account/order-details/*') )
            @include('pages.frontend.user-account.order-details')
          @elseif(Request::is('user/account/cancel-orders/*'))
            @include('pages.frontend.user-account.cancel-order')
          @endif
@endsection
@section('scripts')

@endsection